spring:
  profiles:
    active: dev
  application:
    name: eureka-server-8001 #这个竟然是服务名，消费端通过 http://EUREKA-SERVER-8001  进行方法


server:
  port: 8001

## eureka 服务提供者
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-register-7001:7001/eureka/
  instance:
    prefer-ip-address: true
#    instance-id: producer-8001 #那这个是什么

logging:
  config: classpath:config/logback-acfo.xml