#server:
#  port: 6001

spring:
#  application:
#    name: yuanlai-dao-6001
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/yuanlai?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 30
      max-active: 30
      min-idle: 30
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      filter:
        stat:
          enabled: true
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 10000
        wall:
          enabled: true
        log4j2:
          enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  params: count=countSql
#  support-methods-arguments: true
